### ISSUE TITLE
s3_bucket.objects.all() returns []

### ISSUE THREAD

**Issue by ThibaultLemaire** [terrycain/aioboto3#186] opened 2020-01-22 13:58 UTC
* Async AWS SDK for Python version: 6.4.1
* Python version: 3.7.6
* Operating System: Linux 4.19.96 #1-NixOS SMP Tue Jan 14 19:07:09 UTC 2020 x86_64 GNU/Linux

### Description

I'd like to list the objects in my bucket to -- say -- delete them in order to delete the bucket, but I can't because the list operation returns an empty list.

I noticed this operation isn't `await`able, so I guess this is just not implemented ?

Following is the test that shows the faulty behaviour. You'll need `pytest-asyncio`. Be aware that ***this will create and delete an s3 bucket*** for the purposes of the test.

I'm not testing the expected behaviour because then I wouldn't be able to delete the test bucket.

### What I Did

``` python
@pytest.mark.asyncio
async def test_aioboto3_s3_bucket_list_objects(test_bucket):
    created_obj = await test_bucket.put_object(Key="test", Body="test data")
    objects = list(test_bucket.objects.all())
    assert objects == []  # This shouldn't be empty at all
    await created_obj.delete()


@pytest.fixture
async def test_bucket(s3_bucket_name, aio_s3_client, aio_s3_resource):
    region = aio_s3_client.meta.region_name
    response = await aio_s3_client.create_bucket(
        Bucket=s3_bucket_name,
        CreateBucketConfiguration=dict(LocationConstraint=region),
    )
    assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
    yield aio_s3_resource.Bucket(s3_bucket_name)
    await aio_s3_client.delete_bucket(Bucket=s3_bucket_name)


@pytest.fixture
def s3_bucket_name():
    # Hardcoded for the example, mine is Faker-generated
    return "test-bucket-zqxvp9zl84p4"


@pytest.fixture
async def aio_s3_client():
    async with aioboto3.client("s3") as s3_client:
        yield s3_client


@pytest.fixture
async def aio_s3_resource():
    async with aioboto3.resource("s3") as s3_resource:
        yield s3_resource
```

**Comment by terrycain** [comment] 2020-01-22 16:48
Isn't this a duplicate of #181 ?

**Comment by ThibaultLemaire** [comment] 2020-01-22 18:07
Not exactly no, the deletion was only an example, it's not my actual use-case (and I don't have any exception raised, contrary to #181).

If both can be solved in the same though way, I'm happy with to roll with that.

**Comment by terrycain** [comment] 2020-02-19 19:06
I have a feeling both can be solved the same way, but i'll need to look into it again

**Closed** 2020-02-20 11:49 UTC

**Comment by terrycain** [comment] 2020-02-20 11:56
Should be fixed by v6.5.0 can you test it out? If it doesn't work can you reopen this ticket with the issue.
